language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test:coverage
  - npm run build
  - npm run build:css
  - npm run build-demo
deploy:
  provider: surge
  project: ./example/dist/
  domain: gif-picker.surge.sh
  on:
    branch: master
