language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test:coverage
  - npm run build
  - npm run build:css
  - npm run build-demo
  - npm run codecov
deploy:
  provider: surge
  skip_cleanup: true
  project: ./example/dist/
  domain: gif-picker.surge.sh
notifications:
  email:
    on_success: info@davidverhulst.be # default: change
    on_failure: info@davidverhulst.be # default: change
