// flow-typed signature: 58af8eabf8f8bd27ac98e2846d86f97d
// flow-typed version: <<STUB>>/stylelint-config-airbnb_v0.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-airbnb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-airbnb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-airbnb/test/test-base' {
  declare module.exports: any;
}

declare module 'stylelint-config-airbnb/test/test-sass' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-airbnb/index' {
  declare module.exports: $Exports<'stylelint-config-airbnb'>;
}
declare module 'stylelint-config-airbnb/index.js' {
  declare module.exports: $Exports<'stylelint-config-airbnb'>;
}
declare module 'stylelint-config-airbnb/test/test-base.js' {
  declare module.exports: $Exports<'stylelint-config-airbnb/test/test-base'>;
}
declare module 'stylelint-config-airbnb/test/test-sass.js' {
  declare module.exports: $Exports<'stylelint-config-airbnb/test/test-sass'>;
}
